#ifndef _WA_CURSOR_H_
#define _WA_CURSOR_H_

#include "wa.h"

enum wa_cursor_shape
{
    WA_CURSOR_DEFAULT = 0,
    WA_CURSOR_CONTEXT_MENU,
    WA_CURSOR_HELP,
    WA_CURSOR_POINTER,
    WA_CURSOR_PROGRESS,
    WA_CURSOR_WAIT,
    WA_CURSOR_CELL,
    WA_CURSOR_CROSSHAIR,
    WA_CURSOR_TEXT,
    WA_CURSOR_VERTICAL_TEXT,
    WA_CURSOR_ALIAS,
    WA_CURSOR_COPY,
    WA_CURSOR_MOVE,
    WA_CURSOR_NO_DROP,
    WA_CURSOR_NOT_ALLOWED,
    WA_CURSOR_GRAB,
    WA_CURSOR_GRABBING,
    WA_CURSOR_E_RESIZE,
    WA_CURSOR_N_RESIZE,
    WA_CURSOR_NE_RESIZE,
    WA_CURSOR_NW_RESIZE,
    WA_CURSOR_S_RESIZE,
    WA_CURSOR_SE_RESIZE,
    WA_CURSOR_SW_RESIZE,
    WA_CURSOR_W_RESIZE,
    WA_CURSOR_EW_RESIZE,
    WA_CURSOR_NS_RESIZE,
    WA_CURSOR_NESW_RESIZE,
    WA_CURSOR_NWSE_RESIZE,
    WA_CURSOR_COL_RESIZE,
    WA_CURSOR_ROW_RESIZE,
    WA_CURSOR_ALL_SCROLL,
    WA_CURSOR_ZOOM_IN,
    WA_CURSOR_ZOOM_OUT,
};

void wa_set_cursor_shape(wa_window_t* window, enum wa_cursor_shape shape);

#endif // _WA_CURSOR_H_
